- name: Pull Docker Image from Docker Hub
  hosts: localhost
  become: false
  connection: local
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: 'nishthapaul/hello-world-jenkin-project'
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result
        
    - name: Start Docker service
      service:
        name: docker
        state: started
    # - name: Running container
    #   shell: docker run -it -d --name hw-container nishthapaul/hello-world-jenkin-project
    - name: Create Docker Container
      docker_container:
        name: hw-container
        image: nishthapaul/hello-world-jenkin-project
        state: started
