- name: Pull Docker Image from Docker Hub
  hosts: localhost
  become: false
  connection: local
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: 'nishthapaul/hello-world-jenkin-project'
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Removing container if already exists
      shell: 
        container_name="hw-container"
        if docker ps -a --format '{{.Names}}' | grep -Eq "^$container_name$"; then
            docker rm -f "$container_name"
            echo "Container $container_name removed."
        else
            echo "Container $container_name does not exist."
        fi
        # docker rm hw-container

    - name: Running container
      shell: docker run -it -d --name hw-container nishthapaul/hello-world-jenkin-project
